(() => {
  "use strict";

  // 병과 설명의 수치도 balance.js 단일 원본에서 끌어온다 (로비 표기와 실제 수치가 어긋나지 않게).
  const B = window.BREACHLINE_BALANCE;

  const operators = [
    {
      id: "gunslinger",
      legacyIds: ["gemini"],
      name: "JOHN ICK",
      koreanName: "존 익",
      symbol: "🔫",
      role: "기동 공격",
      weapon: "DUAL PISTOLS",
      weaponId: "dual_pistols",
      baseWeapon: "smg",
      color: "#ffd166",
      tagline: "두 자루, 하나의 진입각",
      desc: "800 RPM 쌍권총을 교대로 발사하고, 현재 이동 입력 방향으로 회전 사격하는 건카타 돌진을 수행한다.",
      traits: [`좌클릭: 쌍권총 교대 사격 · ${B.operators.gunslinger.weapon.rpm} RPM`, `우클릭: 이동키 방향 건카타 돌진 · 범위 ${B.operators.gunslinger.gunKata.damage} 피해`, `특수능력 재사용 대기시간 ${B.operators.gunslinger.gunKata.cooldown}초`],
      controls: { primary: "쌍권총", secondary: "건카타 대쉬", ability: "-" },
      stats: { 화력: 3, 기동: 5, 생존: 3 },
      implemented: true,
    },
    {
      id: "bulwark",
      name: "IRON",
      koreanName: "아이언",
      symbol: "🛡️",
      role: "전선 방어",
      weapon: "SHIELD & PISTOL",
      weaponId: "shield_pistol",
      baseWeapon: "rifle",
      color: "#7ea8ff",
      tagline: "정면은 곧 안전지대",
      desc: "우클릭 홀드로 라인하르트식 방벽(체력 250)을 전방 60도에 전개한다. 전개 중엔 이동이 느려지고, 섬광방패는 전방 부채꼴을 즉시 제압한다.",
      traits: [`좌클릭: 권총 · ${B.operators.bulwark.weapon.damage} 피해`, `우클릭 홀드: 방벽 전개 · 체력 ${B.operators.bulwark.barrier.maxHp} · 이동 -50%`, `SPACE: 전방 부채꼴 섬광방패 · 쿨다운 ${B.skills.cooldown}초`],
      controls: { primary: "권총", secondary: "방벽 홀드", ability: "섬광방패" },
      stats: { 화력: 2, 기동: 2, 생존: 5 },
      implemented: true,
    },
    {
      id: "sentinel",
      legacyIds: ["longshot"],
      name: "RB-08",
      koreanName: "로봇",
      symbol: "🤖",
      role: "관통 정찰",
      weapon: "RAILGUN",
      weaponId: "railgun",
      baseWeapon: "rifle",
      color: "#55f0b0",
      tagline: "벽 너머의 열원을 읽는다",
      desc: "수렴 레이저로 1초 충전을 예고한 뒤 최대 식별 거리까지 벽을 관통하는 레일건을 발사하고, 벽 너머 적과 시야 부채꼴을 탐지한다.",
      traits: [`좌클릭 홀드: ${B.operators.sentinel.railgun.chargeTime}초 충전 · ${B.operators.sentinel.weapon.damage} 피해`, `레일건 히트스캔 · 최대 시야 사거리 · 벽 관통`, `SPACE: ${B.operators.sentinel.reveal.duration}초 투시 · 쿨다운 ${B.operators.sentinel.reveal.cooldown}초`],
      controls: { primary: "충전 레일건", secondary: "-", ability: "투시 스캔" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "soldier",
      legacyIds: ["vulcan", "wasp"],
      name: "SOLDIER",
      koreanName: "군인",
      symbol: "🪖",
      role: "범용 돌격",
      weapon: "ASSAULT RIFLE",
      weaponId: "rifle",
      baseWeapon: "rifle",
      color: "#6de6df",
      tagline: "교전과 전술 장비의 기준점",
      desc: "30발 돌격소총과 섬광탄 두 개를 운용하는 표준 병과다.",
      traits: [`좌클릭: 돌격소총 · ${B.operators.soldier.weapon.damage} 피해`, `2: 섬광탄 · ${B.gadgets.flash.count}개 보유`, `투척 준비 중 기본 공격 불가`],
      controls: { primary: "돌격소총", secondary: "투척 장비", ability: "-" },
      stats: { 화력: 4, 기동: 3, 생존: 3 },
      implemented: true,
    },
    {
      id: "frog",
      name: "FROG",
      koreanName: "개구리",
      symbol: "🐸",
      role: "기동 제어",
      weapon: "BUBBLE SPRAYER",
      weaponId: "frog_tongue",
      baseWeapon: "frog",
      color: "#67e887",
      tagline: "거품으로 늦추고 혀로 날아든다",
      desc: "다섯 갈래 거품으로 적의 이동을 늦추고, 혀를 벽에 붙여 전장을 가로지른다. 부착 중에는 초록색 점선 안을 360도로 보고, 회전하며 가까운 적을 자동 공격한다.",
      traits: [`좌클릭: 거품 ${B.operators.frog.weapon.pellets}펠릿 · 펠릿당 ${B.operators.frog.weapon.damage} 피해`, `SPACE: 쿨다운 없는 벽 혀 · A/D 스윙`, `부착 중 우클릭 당기기 · 회전 중 자동 거품`],
      controls: { primary: "거품 발사", secondary: "혀 길이 당기기", ability: "벽 혀 스윙" },
      stats: { 화력: 3, 기동: 5, 생존: 2 },
      implemented: true,
    },
    {
      id: "reaper",
      name: "REAPER",
      koreanName: "사신",
      symbol: "💀",
      role: "근접 소환",
      weapon: "GREAT SCYTHE",
      weaponId: "scythe",
      baseWeapon: "shotgun",
      color: "#c59bff",
      tagline: "생명을 지불하고 전선을 늘린다",
      desc: "대형 낫으로 전방을 베고, 우클릭으로 낫을 부메랑처럼 던진다. 체력 25를 소모해 추적형 언데드 세 마리를 소환한다.",
      traits: [`좌클릭: 전방 부채꼴 · ${B.operators.reaper.weapon.damage} 피해`, `우클릭: 낫 투척 · 벽 관통 · 회수 전 근접 불가`, `SPACE: 체력 ${B.operators.reaper.summon.costHp} 소모 · 언데드 3기`],
      controls: { primary: "대형 낫", secondary: "낫 투척", ability: "언데드 소환" },
      stats: { 화력: 4, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "hunter",
      legacyIds: ["buckshot"],
      name: "HUNTER",
      koreanName: "사냥꾼",
      symbol: "🤠",
      role: "근접 돌파",
      weapon: "DOUBLE BARREL",
      weaponId: "shotgun",
      baseWeapon: "shotgun",
      color: "#ffab63",
      tagline: "두 발 안에 거리를 끝낸다",
      desc: "두 발짜리 더블 배럴 산탄총과 공격을 무시하는 전방 대쉬로 근접전을 강제한다.",
      traits: [`좌클릭: 5펠릿 · 펠릿당 ${B.operators.hunter.weapon.damage} 피해 · 빠른 연사`, `SPACE: 이동키 방향 무적 대쉬 · 쿨다운 ${B.operators.hunter.dash.cooldown}초`, `탄창 ${B.operators.hunter.weapon.magSize}발 · 재장전 ${B.operators.hunter.weapon.reload}초`],
      controls: { primary: "더블 배럴", secondary: "-", ability: "무적 대쉬" },
      stats: { 화력: 5, 기동: 4, 생존: 3 },
      implemented: true,
    },
    {
      id: "ninja",
      legacyIds: ["edge", "shade"],
      name: "NINJA",
      koreanName: "닌자",
      symbol: "🥷",
      role: "암살 교란",
      weapon: "KATANA / DAGGERS",
      weaponId: "katana",
      baseWeapon: "shotgun",
      color: "#ff5f6d",
      tagline: "연막 속에서 사거리의 규칙을 바꾼다",
      desc: "카타나로 전방을 베고 집탄된 세 갈래 단도와 강화 연막으로 접근 경로를 만든다.",
      traits: [`좌클릭: 카타나 부채꼴 · ${B.operators.ninja.weapon.damage} 피해`, `우클릭: 3방향 단도 · 각 ${B.operators.ninja.dagger.damage} 피해`, `SPACE: 반경 ${B.operators.ninja.smoke.radius} · ${B.operators.ninja.smoke.duration}초 연막`],
      controls: { primary: "카타나", secondary: "삼연 단도", ability: "강화 연막" },
      stats: { 화력: 4, 기동: 4, 생존: 2 },
      implemented: true,
    },
    {
      id: "sniper",
      name: "SNIPER",
      koreanName: "스나이퍼",
      symbol: "😎",
      role: "장거리 저격",
      weapon: "BOLT-ACTION RIFLE",
      weaponId: "bolt_action",
      baseWeapon: "rifle",
      color: "#9ef0ff",
      tagline: "한 발을 위해 더 멀리 본다",
      desc: "80 피해의 볼트액션 저격총을 사용한다. 시야가 넓은 대신 이동속도가 25% 느리다.",
      traits: [`좌클릭: ${B.operators.sniper.weapon.damage} 피해 고속 투사체`, `기본 재장전 사용 · ${B.operators.sniper.weapon.reload}초`, `패시브: 시야 ${B.vision.camera.sniperScale}배 · 이동속도 -25%`],
      controls: { primary: "볼트액션", secondary: "-", ability: "확장 시야(패시브)" },
      stats: { 화력: 5, 기동: 1, 생존: 2 },
      implemented: true,
    },
    {
      id: "demolitionist",
      legacyIds: ["mortar"],
      name: "DEMOLITIONIST",
      koreanName: "폭탄마",
      symbol: "🧨",
      role: "폭발 제압",
      weapon: "6-SHOT GRENADE LAUNCHER",
      weaponId: "grenade_launcher",
      baseWeapon: "shotgun",
      color: "#ffa8f0",
      tagline: "엄폐물이 아니라 구역을 공격한다",
      desc: "유효 사거리 안의 지정 착탄점으로 6연장 유탄을 발사한다. 유탄은 비행 중 범위를 숨기고 착탄 즉시 폭발하며, 수류탄은 2번키로 준비해 투척한다.",
      traits: [`좌클릭: 지정 착탄 · 즉시 폭발 · 반경 ${B.gadgets.launcher.radius} · ${B.gadgets.launcher.damage} 피해`, `유탄 사거리 ${B.operators.demolitionist.weapon.range} · 착탄점 범위 사전 표시`, `2번키: 반경 ${B.gadgets.frag.radius} · ${B.gadgets.frag.damage} 피해 수류탄 ${B.gadgets.frag.count}개 (투척)`],
      controls: { primary: "6연장 유탄", secondary: "-", ability: "-" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
  ];

  const byId = Object.fromEntries(operators.map((operator) => [operator.id, operator]));
  const legacy = {};
  for (const operator of operators) {
    for (const id of operator.legacyIds || []) legacy[id] = operator.id;
  }

  const resolveId = (id) => (byId[id] ? id : legacy[id] || "soldier");
  const find = (id) => byId[resolveId(id)] || byId.soldier;

  window.BREACHLINE_OPERATORS = Object.freeze(operators);
  window.BREACHLINE_OPERATOR_BY_ID = Object.freeze(byId);
  window.BREACHLINE_OPERATOR_LEGACY_IDS = Object.freeze(legacy);
  window.resolveBreachlineOperatorId = resolveId;
  window.findBreachlineOperator = find;
})();
