(() => {
  "use strict";

  const operators = [
    {
      id: "gunslinger",
      legacyIds: ["gemini"],
      name: "JOHN ICK",
      koreanName: "존 익",
      symbol: "🔫",
      role: "기동 공격",
      weapon: "DUAL PISTOLS",
      weaponId: "dual_pistols",
      baseWeapon: "smg",
      color: "#ffd166",
      tagline: "두 자루, 하나의 진입각",
      desc: "800 RPM 쌍권총을 교대로 발사하고, 마우스 방향으로 회전 사격하는 건카타 돌진을 수행한다.",
      traits: ["좌클릭: 쌍권총 교대 사격 · 800 RPM", "우클릭: 건카타 돌진 · 범위 40 피해", "특수능력 재사용 대기시간 5초"],
      controls: { primary: "쌍권총", secondary: "건카타 대쉬", ability: "-" },
      stats: { 화력: 3, 기동: 5, 생존: 3 },
      implemented: true,
    },
    {
      id: "bulwark",
      name: "IRON",
      koreanName: "아이언",
      symbol: "🛡️",
      role: "전선 방어",
      weapon: "SHIELD & PISTOL",
      weaponId: "shield_pistol",
      baseWeapon: "rifle",
      color: "#7ea8ff",
      tagline: "정면은 곧 안전지대",
      desc: "짧은 사거리의 권총을 사용하며 넓은 방패로 정면을 방어하는 대신 시야각이 20도로 제한된다.",
      traits: ["좌클릭: 권총 · 10 피해", "패시브: 정면 좌우 45도 공격 차단 · 시야각 20도", "재장전 2.5초 · 탄약 무제한"],
      controls: { primary: "방패 권총", secondary: "-", ability: "정면 방패(패시브)" },
      stats: { 화력: 2, 기동: 2, 생존: 5 },
      implemented: true,
    },
    {
      id: "sentinel",
      legacyIds: ["longshot"],
      name: "RB-08",
      koreanName: "로봇",
      symbol: "🤖",
      role: "관통 정찰",
      weapon: "RAILGUN",
      weaponId: "railgun",
      baseWeapon: "rifle",
      color: "#55f0b0",
      tagline: "벽 너머의 열원을 읽는다",
      desc: "수렴 레이저로 1초 충전을 예고한 뒤 벽을 관통하는 단거리 레일건을 발사하고, 잠시 벽 너머 적을 탐지한다.",
      traits: ["좌클릭 홀드: 1초 충전 · 40 피해", "레일건 히트스캔 · 벽 관통", "SPACE: 3초 투시 · 쿨다운 5초"],
      controls: { primary: "충전 레일건", secondary: "-", ability: "투시 스캔" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "soldier",
      legacyIds: ["vulcan", "wasp"],
      name: "SOLDIER",
      koreanName: "군인",
      symbol: "🪖",
      role: "범용 돌격",
      weapon: "ASSAULT RIFLE",
      weaponId: "rifle",
      baseWeapon: "rifle",
      color: "#6de6df",
      tagline: "교전과 전술 장비의 기준점",
      desc: "30발 돌격소총과 섬광탄 두 개를 운용하는 표준 병과다.",
      traits: ["좌클릭: 돌격소총 · 20 피해", "2: 섬광탄 · 2개 보유", "투척 준비 중 기본 공격 불가"],
      controls: { primary: "돌격소총", secondary: "투척 장비", ability: "-" },
      stats: { 화력: 4, 기동: 3, 생존: 3 },
      implemented: true,
    },
    {
      id: "frog",
      name: "FROG",
      koreanName: "개구리",
      symbol: "🐸",
      role: "기동 제어",
      weapon: "BUBBLE SPRAYER",
      weaponId: "frog_tongue",
      baseWeapon: "frog",
      color: "#67e887",
      tagline: "거품으로 늦추고 혀로 날아든다",
      desc: "다섯 갈래 거품으로 적의 이동을 늦추고, 혀를 벽에 붙여 전장을 가로지른다. 부착 중에는 초록색 점선 안을 360도로 보고, 회전하며 가까운 적을 자동 공격한다.",
      traits: ["좌클릭: 거품 5펠릿 · 펠릿당 4 피해", "SPACE: 쿨다운 없는 벽 혀 · A/D 스윙", "부착 중 우클릭 당기기 · 회전 중 자동 거품"],
      controls: { primary: "거품 발사", secondary: "혀 길이 당기기", ability: "벽 혀 스윙" },
      stats: { 화력: 3, 기동: 5, 생존: 2 },
      implemented: true,
    },
    {
      id: "reaper",
      name: "REAPER",
      koreanName: "사신",
      symbol: "💀",
      role: "근접 소환",
      weapon: "GREAT SCYTHE",
      weaponId: "scythe",
      baseWeapon: "shotgun",
      color: "#c59bff",
      tagline: "생명을 지불하고 전선을 늘린다",
      desc: "대형 낫으로 전방을 베고 체력 25를 소모해 추적형 언데드 세 마리를 소환한다.",
      traits: ["좌클릭: 전방 부채꼴 · 30 피해", "SPACE: 체력 25 소모 · 언데드 3기", "소환 쿨타임 5초 · 체력 25 이하 사용 불가"],
      controls: { primary: "대형 낫", secondary: "-", ability: "언데드 소환" },
      stats: { 화력: 4, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "hunter",
      legacyIds: ["buckshot"],
      name: "HUNTER",
      koreanName: "사냥꾼",
      symbol: "🤠",
      role: "근접 돌파",
      weapon: "DOUBLE BARREL",
      weaponId: "shotgun",
      baseWeapon: "shotgun",
      color: "#ffab63",
      tagline: "두 발 안에 거리를 끝낸다",
      desc: "두 발짜리 더블 배럴 산탄총과 공격을 무시하는 전방 대쉬로 근접전을 강제한다.",
      traits: ["좌클릭: 5펠릿 · 펠릿당 20 피해 · 빠른 연사", "SPACE: 마우스 방향 무적 대쉬 · 쿨다운 5초", "탄창 2발 · 재장전 2.5초"],
      controls: { primary: "더블 배럴", secondary: "-", ability: "무적 대쉬" },
      stats: { 화력: 5, 기동: 4, 생존: 3 },
      implemented: true,
    },
    {
      id: "ninja",
      legacyIds: ["edge", "shade"],
      name: "NINJA",
      koreanName: "닌자",
      symbol: "🥷",
      role: "암살 교란",
      weapon: "KATANA / DAGGERS",
      weaponId: "katana",
      baseWeapon: "shotgun",
      color: "#ff5f6d",
      tagline: "연막 속에서 사거리의 규칙을 바꾼다",
      desc: "카타나로 전방을 베고 집탄된 세 갈래 단도와 강화 연막으로 접근 경로를 만든다.",
      traits: ["좌클릭: 카타나 부채꼴 · 30 피해", "우클릭: 3방향 단도 · 각 15 피해", "SPACE: 반경 225 · 5초 연막"],
      controls: { primary: "카타나", secondary: "삼연 단도", ability: "강화 연막" },
      stats: { 화력: 4, 기동: 4, 생존: 2 },
      implemented: true,
    },
    {
      id: "sniper",
      name: "SNIPER",
      koreanName: "스나이퍼",
      symbol: "😎",
      role: "장거리 저격",
      weapon: "BOLT-ACTION RIFLE",
      weaponId: "bolt_action",
      baseWeapon: "rifle",
      color: "#9ef0ff",
      tagline: "한 발을 위해 더 멀리 본다",
      desc: "80 피해의 볼트액션 저격총을 사용한다. 시야가 넓은 대신 이동속도가 25% 느리다.",
      traits: ["좌클릭: 80 피해 고속 투사체", "기본 재장전 사용 · 0.9초", "패시브: 시야 1.5배 · 이동속도 -25%"],
      controls: { primary: "볼트액션", secondary: "-", ability: "확장 시야(패시브)" },
      stats: { 화력: 5, 기동: 1, 생존: 2 },
      implemented: true,
    },
    {
      id: "demolitionist",
      legacyIds: ["mortar"],
      name: "DEMOLITIONIST",
      koreanName: "폭탄마",
      symbol: "🧨",
      role: "폭발 제압",
      weapon: "6-SHOT GRENADE LAUNCHER",
      weaponId: "grenade_launcher",
      baseWeapon: "shotgun",
      color: "#ffa8f0",
      tagline: "엄폐물이 아니라 구역을 공격한다",
      desc: "차징 없이 6연장 유탄발사기로 수류탄형 투사체를 발사하며 우클릭으로 고위력 수류탄 두 개를 투척한다.",
      traits: ["좌클릭: 반경 67 · 40 피해 유탄", "우클릭: 반경 100 · 60 피해 수류탄", "수류탄 2개 보유"],
      controls: { primary: "6연장 유탄", secondary: "수류탄", ability: "-" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
  ];

  const byId = Object.fromEntries(operators.map((operator) => [operator.id, operator]));
  const legacy = {};
  for (const operator of operators) {
    for (const id of operator.legacyIds || []) legacy[id] = operator.id;
  }

  const resolveId = (id) => (byId[id] ? id : legacy[id] || "soldier");
  const find = (id) => byId[resolveId(id)] || byId.soldier;

  window.BREACHLINE_OPERATORS = Object.freeze(operators);
  window.BREACHLINE_OPERATOR_BY_ID = Object.freeze(byId);
  window.BREACHLINE_OPERATOR_LEGACY_IDS = Object.freeze(legacy);
  window.resolveBreachlineOperatorId = resolveId;
  window.findBreachlineOperator = find;
})();
