(() => {
  "use strict";

  // 병과 설명의 수치도 balance.js 단일 원본에서 끌어온다 (로비 표기와 실제 수치가 어긋나지 않게).
  const B = window.BREACHLINE_BALANCE;

  const operators = [
    {
      id: "gunslinger",
      legacyIds: ["gemini"],
      name: "JOHN ICK",
      koreanName: "존 익",
      symbol: "🔫",
      role: "기동 공격",
      weapon: "DUAL PISTOLS",
      weaponId: "dual_pistols",
      baseWeapon: "smg",
      color: "#ffd166",
      tagline: "두 자루, 하나의 진입각",
      desc: "800 RPM 쌍권총을 교대로 발사하고, 우클릭으로 전방 부채꼴을 쌍권총으로 난사한다. SPACE 로 이동 방향으로 회전 사격하는 건카타 돌진을 수행한다.",
      traits: [`좌클릭: 쌍권총 교대 사격 · ${B.operators.gunslinger.weapon.rpm} RPM`, `우클릭: 부채꼴 난사 · ${B.operators.gunslinger.spray.shots}발 · 쿨다운 ${B.operators.gunslinger.spray.cooldown}초`, `SPACE: 건카타 돌진 · 범위 ${B.operators.gunslinger.gunKata.damage} 피해 · 쿨다운 ${B.operators.gunslinger.gunKata.cooldown}초`],
      controls: { primary: "쌍권총", secondary: "부채꼴 난사", ability: "건카타 대쉬" },
      stats: { 화력: 3, 기동: 5, 생존: 3 },
      implemented: true,
    },
    {
      id: "bulwark",
      name: "IRON",
      koreanName: "아이언",
      symbol: "🛡️",
      role: "전선 방어",
      weapon: "SHIELD & PISTOL",
      weaponId: "shield_pistol",
      baseWeapon: "rifle",
      color: "#7ea8ff",
      tagline: "정면은 곧 안전지대",
      desc: "우클릭 홀드로 라인하르트식 방벽(체력 250)을 전방 60도에 전개한다. 전개 중엔 이동이 느려지고, 섬광방패는 전방 부채꼴을 즉시 제압한다.",
      traits: [`좌클릭: 방패를 든 채 LMG 연사 · ${B.operators.bulwark.weapon.damage} 피해 · ${B.operators.bulwark.weapon.rpm} RPM`, `100발 탄창 · 넓은 탄퍼짐 · 예비탄 무한 · 시야각 ${B.vision.shieldViewDegrees}도`, `우클릭 홀드 + 좌클릭: 방벽을 유지하며 연속 사격`],
      controls: { primary: "권총", secondary: "방벽 홀드", ability: "섬광방패" },
      stats: { 화력: 2, 기동: 2, 생존: 5 },
      implemented: true,
    },
    {
      id: "sentinel",
      legacyIds: ["longshot"],
      name: "RB-08",
      koreanName: "로봇",
      symbol: "🤖",
      role: "관통 정찰",
      weapon: "RAILGUN",
      weaponId: "railgun",
      baseWeapon: "rifle",
      color: "#55f0b0",
      tagline: "벽 너머의 열원을 읽는다",
      desc: "수렴 레이저로 1초 충전을 예고한 뒤 최대 식별 거리까지 벽을 관통하는 레일건을 발사하고, 우클릭 홀드로 3초를 충전해 넓은 보라색 관통 레이저를 발사한다. 벽 너머 적과 시야 부채꼴을 탐지한다.",
      traits: [`좌클릭 홀드: ${B.operators.sentinel.railgun.chargeTime}초 충전 · ${B.operators.sentinel.weapon.damage} 피해`, `우클릭 홀드: ${B.operators.sentinel.heavyLaser.chargeTime}초 충전 · 넓은 보라색 레이저 · 쿨다운 ${B.operators.sentinel.heavyLaser.cooldown}초`, `SPACE: ${B.operators.sentinel.reveal.duration}초 투시 · 쿨다운 ${B.operators.sentinel.reveal.cooldown}초`],
      controls: { primary: "충전 레일건", secondary: "헤비 레이저", ability: "투시 스캔" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "soldier",
      legacyIds: ["vulcan", "wasp"],
      name: "SOLDIER",
      koreanName: "군인",
      symbol: "🪖",
      role: "범용 돌격",
      weapon: "ASSAULT RIFLE",
      weaponId: "rifle",
      baseWeapon: "rifle",
      color: "#6de6df",
      tagline: "교전과 전술 장비의 기준점",
      desc: "30발 돌격소총을 운용하는 표준 병과다. 우클릭으로 개수 제한 없는 섬광탄을 던지고, SPACE 로 이동속도와 피해를 강화한다.",
      traits: [`좌클릭: 돌격소총 · ${B.operators.soldier.weapon.damage} 피해`, `우클릭: 섬광탄 투척 · 무제한 · 쿨다운 ${B.operators.soldier.flashCooldown}초`, `SPACE: 신체강화 · ${B.operators.soldier.enhance.duration}초 이동·피해 부스트 · 쿨다운 ${B.operators.soldier.enhance.cooldown}초`],
      controls: { primary: "돌격소총", secondary: "섬광탄", ability: "신체강화" },
      stats: { 화력: 4, 기동: 3, 생존: 3 },
      implemented: true,
    },
    {
      id: "frog",
      name: "FROG",
      koreanName: "개구리",
      symbol: "🐸",
      role: "기동 제어",
      weapon: "BUBBLE SPRAYER",
      weaponId: "frog_tongue",
      baseWeapon: "frog",
      color: "#67e887",
      tagline: "거품으로 늦추고 혀로 날아든다",
      desc: "다섯 갈래 거품으로 적의 이동을 늦추고, 혀를 벽에 붙여 전장을 가로지른다. 부착 중에는 초록색 점선 안을 360도로 보고, 회전하며 가까운 적을 자동 공격한다.",
      traits: [`좌클릭: 거품 ${B.operators.frog.weapon.pellets}펠릿 · 펠릿당 ${B.operators.frog.weapon.damage} 피해`, `SPACE: 쿨다운 없는 벽 혀 · A/D 스윙`, `부착 중 우클릭 당기기 · 회전 중 자동 거품`],
      controls: { primary: "거품 발사", secondary: "혀 길이 당기기", ability: "벽 혀 스윙" },
      stats: { 화력: 3, 기동: 5, 생존: 2 },
      implemented: true,
    },
    {
      id: "reaper",
      name: "REAPER",
      koreanName: "사신",
      symbol: "💀",
      role: "근접 소환",
      weapon: "GREAT SCYTHE",
      weaponId: "scythe",
      baseWeapon: "shotgun",
      color: "#c59bff",
      tagline: "생명을 지불하고 전선을 늘린다",
      desc: "대형 낫으로 전방을 베고, 우클릭으로 낫을 부메랑처럼 던진다. 체력 25를 소모해 추적형 언데드 세 마리를 소환한다.",
      traits: [`좌클릭: 전방 부채꼴 · ${B.operators.reaper.weapon.damage} 피해`, `우클릭: 낫 투척 · ${B.operators.reaper.scytheThrow.damage} 피해 · 벽 관통 · 회수 전 근접 불가`, `SPACE: 체력 ${B.operators.reaper.summon.costHp} 소모 · 언데드 3기 · 공격당 ${B.operators.reaper.summon.attackDamage} 피해`],
      controls: { primary: "대형 낫", secondary: "낫 투척", ability: "언데드 소환" },
      stats: { 화력: 4, 기동: 2, 생존: 3 },
      implemented: true,
    },
    {
      id: "hunter",
      legacyIds: ["buckshot"],
      name: "HUNTER",
      koreanName: "사냥꾼",
      symbol: "🤠",
      role: "근접 돌파",
      weapon: "DOUBLE BARREL",
      weaponId: "shotgun",
      baseWeapon: "shotgun",
      color: "#ffab63",
      tagline: "두 발 안에 거리를 끝낸다",
      desc: "두 발짜리 더블 배럴 산탄총과 공격을 무시하는 전방 대쉬로 근접전을 강제한다. 우클릭으로 일정 거리 내 적의 위치를 감지한다.",
      traits: [`좌클릭: 5펠릿 · 펠릿당 ${B.operators.hunter.weapon.damage} 피해 · 빠른 연사`, `우클릭: 피냄새 감지 · 거리 ${B.operators.hunter.bloodScent.range} · 쿨다운 ${B.operators.hunter.bloodScent.cooldown}초`, `SPACE: 이동키 방향 무적 대쉬 · 쿨다운 ${B.operators.hunter.dash.cooldown}초`],
      controls: { primary: "더블 배럴", secondary: "피냄새 감지", ability: "무적 대쉬" },
      stats: { 화력: 5, 기동: 4, 생존: 3 },
      implemented: true,
    },
    {
      id: "ninja",
      legacyIds: ["edge", "shade"],
      name: "NINJA",
      koreanName: "닌자",
      symbol: "🥷",
      role: "암살 교란",
      weapon: "KATANA / DAGGERS",
      weaponId: "katana",
      baseWeapon: "shotgun",
      color: "#ff5f6d",
      tagline: "연막 속에서 사거리의 규칙을 바꾼다",
      desc: "카타나로 전방을 베고 집탄된 세 갈래 단도와 강화 연막으로 접근 경로를 만든다.",
      traits: [`좌클릭: 카타나 부채꼴 · ${B.operators.ninja.weapon.damage} 피해`, `우클릭: 3방향 단도 · 각 ${B.operators.ninja.dagger.damage} 피해`, `SPACE: 반경 ${B.operators.ninja.smoke.radius} · ${B.operators.ninja.smoke.duration}초 연막`],
      controls: { primary: "카타나", secondary: "삼연 단도", ability: "강화 연막" },
      stats: { 화력: 4, 기동: 4, 생존: 2 },
      implemented: true,
    },
    {
      id: "sniper",
      name: "SNIPER",
      koreanName: "스나이퍼",
      symbol: "😎",
      role: "장거리 저격",
      weapon: "BOLT-ACTION RIFLE",
      weaponId: "bolt_action",
      baseWeapon: "rifle",
      color: "#9ef0ff",
      tagline: "한 발을 위해 더 멀리 본다",
      desc: "80 피해의 볼트액션 저격총을 사용한다. 우클릭 투망으로 적을 둔화시키며 뒤로 빠지고, SPACE 로 상대에게 보이지 않는 덫을 설치한다. 시야가 넓은 대신 이동속도가 25% 느리다.",
      traits: [`좌클릭: ${B.operators.sniper.weapon.damage} 피해 고속 투사체`, `우클릭: 투망 · ${B.operators.sniper.net.damage} 피해 · 적 ${Math.round((1 - B.operators.sniper.net.slowMult) * 100)}% 둔화 ${B.operators.sniper.net.slowDuration}초 · 후퇴 · 쿨다운 ${B.operators.sniper.net.cooldown}초`, `SPACE: 덫 설치 모드 → ${B.operators.sniper.trap.damage} 피해 · 포박 ${B.operators.sniper.trap.rootDuration}초 · 최대 ${B.operators.sniper.trap.maxActive}개`],
      controls: { primary: "볼트액션", secondary: "투망/덫 설치", ability: "덫 설치 모드" },
      stats: { 화력: 5, 기동: 1, 생존: 2 },
      implemented: true,
    },
    {
      id: "demolitionist",
      legacyIds: ["mortar"],
      name: "DEMOLITIONIST",
      koreanName: "폭탄마",
      symbol: "🧨",
      role: "폭발 제압",
      weapon: "6-SHOT GRENADE LAUNCHER",
      weaponId: "grenade_launcher",
      baseWeapon: "shotgun",
      color: "#ffa8f0",
      tagline: "엄폐물이 아니라 구역을 공격한다",
      desc: "유효 사거리 안의 지정 착탄점으로 6연장 유탄을 발사한다. 우클릭으로 개수 제한 없는 수류탄을 던지고, SPACE 로 조준 방향에 폭발을 일직선으로 연속 투하한다.",
      traits: [`좌클릭: 지정 착탄 · 즉시 폭발 · 반경 ${B.gadgets.launcher.radius} · ${B.gadgets.launcher.damage} 피해`, `우클릭: 반경 ${B.gadgets.frag.radius} · ${B.gadgets.frag.damage} 피해 수류탄 · 무제한 · 쿨다운 ${B.operators.demolitionist.fragCooldown}초`, `SPACE: 직선 폭격 · ${B.operators.demolitionist.barrage.steps}연속 폭발 · 쿨다운 ${B.operators.demolitionist.barrage.cooldown}초`],
      controls: { primary: "6연장 유탄", secondary: "수류탄", ability: "직선 폭격" },
      stats: { 화력: 5, 기동: 2, 생존: 3 },
      implemented: true,
    },
  ];

  const byId = Object.fromEntries(operators.map((operator) => [operator.id, operator]));
  const legacy = {};
  for (const operator of operators) {
    for (const id of operator.legacyIds || []) legacy[id] = operator.id;
  }

  const resolveId = (id) => (byId[id] ? id : legacy[id] || "soldier");
  const find = (id) => byId[resolveId(id)] || byId.soldier;

  window.BREACHLINE_OPERATORS = Object.freeze(operators);
  window.BREACHLINE_OPERATOR_BY_ID = Object.freeze(byId);
  window.BREACHLINE_OPERATOR_LEGACY_IDS = Object.freeze(legacy);
  window.resolveBreachlineOperatorId = resolveId;
  window.findBreachlineOperator = find;
})();
